function probability=DoubleGammaPDF(t,k1,k2,alpha1,alpha2)

  metaData=struct('name', 'Double Gamma',...
                'PDF',   'A*((k1^alpha1/gamma(alpha1))*t^(alpha1-1)*exp(-k1*t))+(1-A)*((k2^alpha2/gamma(alpha2))*t^(alpha2-1)*exp(-k2*t))',...
                     'dataVar','t',...                    
                    'fitVar', 'A,k1,k2,alpha1,alpha2',...
                      'ub',   '1,1000,1000,1000,1000',...
                    'lb',   '0,0,0,0,0',...
                    'guess','.5,10,10,50,2');
 
   if nargin==1;
           probability=metaData;
    return
   else
       probability=A.*((k1.^alpha1./gamma(alpha1)).*t.^(alpha1-1).*exp(-k1.*t))+(1-A).*((k2.^alpha2./gamma(alpha2)).*t.^(alpha2-1).*exp(-k2.*t));
    end