function probability=  GammaPDF(t,k,alpha)

   metaData(1)=struct('name','Gamma Distribution', ...
                    'PDF',   ' (k^alpha/gamma(alpha))*t^(alpha-1)*exp(-k*t)',...
                     'dataVar','t',...                    
                    'fitVar', 'k,alpha',...
                      'ub',   '1000,1000',...
                    'lb',   '0,0',...
                    'guess','50,2');
             
  if nargin==1;
       probability=metaData;
  return
  end
  probability=(k.^alpha./gamma(alpha)).*t.^(alpha-1).*exp(-k.*t);